server:
  error:
    include-message: always
    include-binding-errors: always

spring:
#  thymeleaf:
#      prefix: classpath:/templates/
  datasource:
    password: alex
    url: jdbc:postgresql://localhost:5432/tss
    username: postgres
  jpa:
    hibernate:
      enable_lazy_load_no_trans: true
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
